# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
name: Mark stale issues and pull requests
run-name: "Housekeeping: Mark stale issues and pull requests"

# Run as a daily cron at 1:30 AM
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: "ubuntu-latest"
    permissions:
      issues: "write"
      pull-requests: "write"
    concurrency:
      group: "${{ github.workflow }}"
      cancel-in-progress: true
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ github.token }}
          days-before-close: 30
